package allybank.glossaryupdateprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Glossary implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String termid;
   private java.lang.String termname;
   private java.lang.String associatedBU;
   @org.kie.api.definition.type.Label("Status of approval by Editor")
   private java.lang.Boolean editstatus;
   private java.lang.Boolean reviewstatus;
   private java.lang.Boolean approvestatus;
   private java.lang.Boolean publishstatus;
   private java.lang.Boolean sendtoMDM;

   private java.lang.String reviewer;

   public Glossary()
   {
   }

   public java.lang.String getTermid()
   {
      return this.termid;
   }

   public void setTermid(java.lang.String termid)
   {
      this.termid = termid;
   }

   public java.lang.String getTermname()
   {
      return this.termname;
   }

   public void setTermname(java.lang.String termname)
   {
      this.termname = termname;
   }

   public java.lang.String getAssociatedBU()
   {
      return this.associatedBU;
   }

   public void setAssociatedBU(java.lang.String associatedBU)
   {
      this.associatedBU = associatedBU;
   }

   public java.lang.Boolean getEditstatus()
   {
      return this.editstatus;
   }

   public void setEditstatus(java.lang.Boolean editstatus)
   {
      this.editstatus = editstatus;
   }

   public java.lang.Boolean getReviewstatus()
   {
      return this.reviewstatus;
   }

   public void setReviewstatus(java.lang.Boolean reviewstatus)
   {
      this.reviewstatus = reviewstatus;
   }

   public java.lang.Boolean getApprovestatus()
   {
      return this.approvestatus;
   }

   public void setApprovestatus(java.lang.Boolean approvestatus)
   {
      this.approvestatus = approvestatus;
   }

   public java.lang.Boolean getPublishstatus()
   {
      return this.publishstatus;
   }

   public void setPublishstatus(java.lang.Boolean publishstatus)
   {
      this.publishstatus = publishstatus;
   }

   public java.lang.Boolean getSendtoMDM()
   {
      return this.sendtoMDM;
   }

   public void setSendtoMDM(java.lang.Boolean sendtoMDM)
   {
      this.sendtoMDM = sendtoMDM;
   }

   public java.lang.String getReviewer()
   {
      return this.reviewer;
   }

   public void setReviewer(java.lang.String reviewer)
   {
      this.reviewer = reviewer;
   }

   public Glossary(java.lang.String termid, java.lang.String termname,
         java.lang.String associatedBU, java.lang.Boolean editstatus,
         java.lang.Boolean reviewstatus, java.lang.Boolean approvestatus,
         java.lang.Boolean publishstatus, java.lang.Boolean sendtoMDM,
         java.lang.String reviewer)
   {
      this.termid = termid;
      this.termname = termname;
      this.associatedBU = associatedBU;
      this.editstatus = editstatus;
      this.reviewstatus = reviewstatus;
      this.approvestatus = approvestatus;
      this.publishstatus = publishstatus;
      this.sendtoMDM = sendtoMDM;
      this.reviewer = reviewer;
   }

}